/**
 * Product names and editorial descriptions are proposed display copy.
 * Prices, dimensions, materials, inventory and package quantities were not supplied.
 * A null price means "request a quotation", not free. Enter verified prices only.
 * Images are the user's supplied photographs; visible accessories are not promised.
 */
window.CATALOG = [
  {
    id: 'vas-lilit-flora', name: 'Vas Lilit Flora', category: 'vas',
    subtitle: 'Lekuk organik · Champagne & perak', badge: 'Detail floral',
    price: null, image: 'assets/products/vas-lilit-flora.webp',
    thumbnail: 'assets/products/vas-lilit-flora-thumb.webp',
    alt: 'Sepasang vas champagne dengan lekuk berlubang dan ornamen bunga perak',
    description: 'Lekuk memanjang yang lembut bertemu ornamen floral keperakan. Nuansa champagne memberi aksen hangat untuk pelaminan, aisle, meja tamu, backdrop, maupun dekorasi rumah.',
    note: 'Foto menampilkan sepasang vas. Jumlah per paket dan aksesori yang disertakan perlu dikonfirmasi.',
    color: 'Champagne & perak', styles: ['klasik'], featured: 1,
  },
  {
    id: 'vas-kelopak-antik', name: 'Vas Kelopak Antik', category: 'vas',
    subtitle: 'Siluet kelopak · Nuansa perunggu', badge: 'Gaya klasik',
    price: null, image: 'assets/products/vas-kelopak-antik.webp',
    thumbnail: 'assets/products/vas-kelopak-antik-thumb.webp',
    alt: 'Dua vas pendek berbentuk kelopak dengan warna perunggu antik',
    description: 'Siluet kelopak yang membulat, tepian berornamen, dan warna perunggu antik. Sebuah aksen klasik untuk menyusun komposisi bunga atau melengkapi dekorasi wedding, event, atau ruang.',
    note: 'Foto menampilkan dua vas. Isi paket, ukuran, dan kesesuaian untuk bunga segar perlu dikonfirmasi.',
    color: 'Perunggu antik', styles: ['klasik', 'natural'], featured: 2,
  },
  {
    id: 'vas-gagang-klasik', name: 'Vas Gagang Klasik', category: 'vas',
    subtitle: 'Ornamen berpilin · Nuansa emas', badge: '',
    price: null, image: 'assets/products/vas-gagang-klasik.webp',
    thumbnail: 'assets/products/vas-gagang-klasik-thumb.webp',
    alt: 'Vas tinggi berwarna emas dengan dua gagang berpilin dan kaki persegi',
    description: 'Dua gagang berpilin membingkai bentuk vas yang tinggi dan ramping. Detail berwarna emas menghadirkan karakter tegas untuk dekorasi wedding klasik, glam, atau interior.',
    note: 'Bahan, tinggi, berat, isi paket, dan pilihan warna perlu dikonfirmasi sebelum pemesanan.',
    color: 'Emas', styles: ['klasik'], featured: 3,
  },
  {
    id: 'vas-cahaya-bambu', name: 'Vas Cahaya Bambu', category: 'vas',
    subtitle: 'Potongan organik · Nuansa kayu', badge: 'Nuansa alami',
    price: null, image: 'assets/products/vas-cahaya-bambu.webp',
    thumbnail: 'assets/products/vas-cahaya-bambu-thumb.webp',
    alt: 'Vas dekoratif bergaya bambu dengan potongan organik dan cahaya hangat',
    description: 'Bentuk memanjang bernuansa bambu, potongan organik, dan permainan cahaya hangat pada foto. Menjadi titik perhatian yang tenang di area welcome table, photo booth, backdrop, atau sudut ruang.',
    note: 'Konfirmasikan bahan serta apakah lampu, bunga, dan aksesori pada foto termasuk dalam pembelian.',
    color: 'Cokelat natural', styles: ['natural'], featured: 4,
  },
  {
    id: 'dekorasi-angsa', name: 'Angsa Harmoni', category: 'dekorasi',
    subtitle: 'Siluet angsa · Putih lembut', badge: 'Sudut yang tenang',
    price: null, image: 'assets/products/dekorasi-angsa.webp',
    thumbnail: 'assets/products/dekorasi-angsa-thumb.webp',
    alt: 'Dekorasi angsa putih dengan pasangan angsa membentuk hati di bagian tengah',
    description: 'Komposisi angsa putih dengan detail sayap dan leher yang membentuk hati. Pilihan aksen lembut untuk meja tamu, photo booth, rak pajang, atau dekorasi acara.',
    note: 'Foto menampilkan beberapa komponen. Isi set, ukuran, dan bahan perlu dikonfirmasi.',
    color: 'Putih', styles: ['minimalis'], featured: 5,
  },
  {
    id: 'dekorasi-keong', name: 'Keong Samudra', category: 'dekorasi',
    subtitle: 'Bentuk laut · Putih natural', badge: 'Bentuk organik',
    price: null, image: 'assets/products/dekorasi-keong.webp',
    thumbnail: 'assets/products/dekorasi-keong-thumb.webp',
    alt: 'Dekorasi keong putih dengan bentuk spiral di atas penyangga bernuansa kayu',
    description: 'Bentuk spiral yang terinspirasi dari keong laut dengan warna putih yang tenang. Siluet organik untuk melengkapi venue bernuansa natural/minimalis atau interior.',
    note: 'Bahan, ukuran, dan apakah penyangga serta aksesori termasuk perlu dikonfirmasi.',
    color: 'Putih', styles: ['minimalis', 'natural'], featured: 6,
  },
  {
    id: 'patung-klasik', name: 'Figur Terakota', category: 'dekorasi',
    subtitle: 'Figur klasik · Warna terakota', badge: '',
    price: null, image: 'assets/products/patung-klasik.webp',
    thumbnail: 'assets/products/patung-klasik-thumb.webp',
    alt: 'Dua patung dada figur klasik berwarna terakota di atas meja',
    description: 'Dua figur bergaya klasik dengan detail rambut dan lipatan busana. Warna terakota pada foto menghadirkan kehangatan visual pada meja display, backdrop, atau area dekorasi.',
    note: 'Terakota merujuk pada warna tampilan, bukan jaminan bahan. Isi paket dan bahan perlu dikonfirmasi.',
    color: 'Terakota', styles: ['natural', 'klasik'], featured: 7,
  },
  {
    id: 'patung-domba', name: 'Domba Tanduk', category: 'taman',
    subtitle: 'Figur satwa · Putih & hitam', badge: '',
    price: null, image: 'assets/products/patung-domba.webp',
    thumbnail: 'assets/products/patung-domba-thumb.webp',
    alt: 'Patung domba putih bertanduk melingkar berdiri di atas dasar menyerupai batu',
    description: 'Figur domba dengan tanduk melingkar dan dasar menyerupai batu. Karakter satwa untuk konsep garden wedding, area tematik, taman, atau ruang pajang.',
    note: 'Ketahanan cuaca, kebutuhan pemasangan, dimensi, dan berat belum ditetapkan; konsultasikan sebelum penggunaan luar ruang.',
    color: 'Putih & hitam', styles: ['natural'], featured: 8,
  },
  {
    id: 'patung-harimau', name: 'Harimau Rimba', category: 'taman',
    subtitle: 'Figur satwa · Motif belang', badge: 'Aksen berkarakter',
    price: null, image: 'assets/products/patung-harimau.webp',
    thumbnail: 'assets/products/patung-harimau-thumb.webp',
    alt: 'Patung harimau jingga bermotif belang dalam posisi melangkah di atas batu',
    description: 'Figur harimau dalam posisi melangkah, dengan pola belang dan ekspresi yang tegas. Inspirasi untuk area tematik, garden wedding, atau komposisi taman.',
    note: 'Ukuran, berat, bahan, ketahanan cuaca, dan pemasangan wajib dikonfirmasi secara terpisah.',
    color: 'Jingga & hitam', styles: ['natural'], featured: 9,
  },
  {
    id: 'kepala-harimau', name: 'Wajah Rimba', category: 'taman',
    subtitle: 'Detail satwa · Motif harimau', badge: '',
    price: null, image: 'assets/products/kepala-harimau.webp',
    thumbnail: 'assets/products/kepala-harimau-thumb.webp',
    alt: 'Dekorasi kepala harimau bermulut terbuka dengan motif jingga, putih, dan hitam',
    description: 'Kepala harimau dengan detail mata, bulu, dan ekspresi yang kuat. Aksen dekoratif untuk konsep venue, photo booth, atau area tematik yang berkarakter.',
    note: 'Cara pemasangan, ukuran, bahan, berat, dan kesesuaian untuk luar ruang perlu dikonfirmasi.',
    color: 'Jingga, putih & hitam', styles: ['natural'], featured: 10,
  },
  {
    id: 'garuda-nusantara', name: 'Garuda Nusantara', category: 'trofi',
    subtitle: 'Dekorasi lambang · Nuansa perunggu', badge: '',
    price: null, image: 'assets/products/garuda-nusantara.webp',
    thumbnail: 'assets/products/garuda-nusantara-thumb.webp',
    alt: 'Kumpulan dekorasi Garuda dengan warna perunggu dan perisai berwarna',
    description: 'Dekorasi Garuda bernuansa perunggu dengan detail sayap dan perisai berwarna. Foto digunakan sebagai referensi tampilan produk.',
    note: 'Konfirmasikan ketepatan detail lambang dan tulisan, ukuran, jumlah per paket, serta fungsi pemasangan.',
    color: 'Perunggu', styles: ['klasik'], featured: 11,
  },
  {
    id: 'trofi-salam', name: 'Trofi Salam', category: 'trofi',
    subtitle: 'Bentuk tangan · Pilihan tampilan', badge: '',
    price: null, image: 'assets/products/trofi-salam.webp',
    thumbnail: 'assets/products/trofi-salam-thumb.webp',
    alt: 'Trofi berbentuk tangan dalam warna emas, perak, dan merah dengan alas hitam',
    description: 'Trofi berbentuk tangan dengan alas hitam. Foto memperlihatkan beberapa warna sebagai referensi untuk kebutuhan event, penghargaan, atau suvenir.',
    note: 'Warna yang tersedia, ukuran, jumlah minimum, dan opsi pelat nama perlu dikonfirmasi.',
    color: 'Emas, perak & merah pada foto', styles: ['klasik'], featured: 12,
  },
  {
    id: 'trofi-nusantara', name: 'Trofi Merah Putih', category: 'trofi',
    subtitle: 'Figur dekoratif · Emas & merah putih', badge: '',
    price: null, image: 'assets/products/trofi-nusantara.webp',
    thumbnail: 'assets/products/trofi-nusantara-thumb.webp',
    alt: 'Trofi figur emas berbalut pita merah putih di atas alas hitam',
    description: 'Figur berwarna emas dengan pita merah putih dan alas hitam. Inspirasi desain untuk kebutuhan event, penghargaan, dan suvenir acara.',
    note: 'Tulisan dan identitas pada foto hanya referensi. Konfirmasikan personalisasi, ukuran, bahan, dan waktu pengerjaan.',
    color: 'Emas, merah & putih', styles: ['klasik'], featured: 13,
  },
  {
    id: 'trofi-figur-emas', name: 'Trofi Figur Emas', category: 'trofi',
    subtitle: 'Figur berdiri · Emas & hitam', badge: '',
    price: null, image: 'assets/products/trofi-figur-emas.webp',
    thumbnail: 'assets/products/trofi-figur-emas-thumb.webp',
    alt: 'Kumpulan trofi figur berdiri berwarna emas di atas alas hitam',
    description: 'Siluet figur berdiri dengan warna emas dan alas hitam bertingkat. Foto merupakan referensi tampilan untuk kebutuhan event atau penghargaan.',
    note: 'Bukan klaim produk resmi suatu penyelenggara penghargaan. Detail desain, tulisan pelat, ukuran, dan bahan perlu dikonfirmasi.',
    color: 'Emas & hitam', styles: ['klasik'], featured: 14,
  },

  {
    id: 'plakat-rusa-megah', name: 'Plakat Rusa Megah', category: 'plakat',
    subtitle: 'Figur rusa · Custom tinggi & lebar', badge: 'Bisa custom',
    price: null, image: 'assets/products/plakat-rusa-megah.webp',
    thumbnail: 'assets/products/plakat-rusa-megah.webp',
    alt: 'Plakat figur rusa bertanduk tinggi di atas alas bergaya batu',
    description: 'Figur rusa berdiri dengan tanduk tinggi dan alas bergaya batu. Cocok sebagai referensi karya fiberglass custom untuk area display, event, venue, dekorasi tematik, maupun kebutuhan khusus.',
    note: 'Tinggi dan lebar bisa custom melalui chat WhatsApp. Harga, bahan, finishing, dan waktu pengerjaan dikonfirmasi sebelum produksi.',
    color: 'Cokelat natural', styles: ['natural', 'klasik'], featured: 15,
  },
  {
    id: 'plakat-flamingo', name: 'Plakat Flamingo', category: 'plakat',
    subtitle: 'Figur flamingo · Custom tinggi & lebar', badge: 'Bisa custom',
    price: null, image: 'assets/products/plakat-flamingo.webp',
    thumbnail: 'assets/products/plakat-flamingo.webp',
    alt: 'Kumpulan plakat figur flamingo merah muda berdiri di area dekorasi',
    description: 'Komposisi figur flamingo dengan warna merah muda dan putih yang menonjol. Dapat menjadi referensi plakat fiberglass custom untuk event, dekorasi venue, taman tematik, atau display.',
    note: 'Tinggi dan lebar bisa custom melalui chat WhatsApp. Jumlah, harga, bahan, finishing, dan waktu pengerjaan dikonfirmasi sebelum produksi.',
    color: 'Merah muda & putih', styles: ['natural', 'minimalis'], featured: 16,
  },
  {
    id: 'plakat-donat-pink', name: 'Plakat Donat Pink', category: 'plakat',
    subtitle: 'Bentuk donat · Custom tinggi & lebar', badge: 'Bisa custom',
    price: null, image: 'assets/products/plakat-donat-pink.webp',
    thumbnail: 'assets/products/plakat-donat-pink.webp',
    alt: 'Plakat berbentuk donat besar berwarna pink dengan ornamen taburan warna-warni',
    description: 'Bentuk donat besar berwarna pink dengan detail taburan warna-warni. Cocok sebagai referensi karya custom untuk photobooth, display, dekorasi acara, atau area tematik.',
    note: 'Tinggi dan lebar bisa custom melalui chat WhatsApp. Harga, bahan, finishing, warna, dan waktu pengerjaan dikonfirmasi sebelum produksi.',
    color: 'Pink', styles: ['minimalis'], featured: 17,
  },
  {
    id: 'plakat-kepala-rusa', name: 'Plakat Kepala Rusa', category: 'plakat',
    subtitle: 'Dekorasi dinding · Custom tinggi & lebar', badge: 'Bisa custom',
    price: null, image: 'assets/products/plakat-kepala-rusa.webp',
    thumbnail: 'assets/products/plakat-kepala-rusa.webp',
    alt: 'Plakat kepala rusa bertanduk terpasang pada panel hitam di dinding',
    description: 'Figur kepala rusa bertanduk dengan panel belakang berwarna gelap. Referensi untuk dekorasi dinding, venue, ruang tematik, maupun pesanan fiberglass custom.',
    note: 'Tinggi dan lebar bisa custom melalui chat WhatsApp. Sistem pemasangan, harga, bahan, finishing, dan waktu pengerjaan dikonfirmasi sebelum produksi.',
    color: 'Cokelat & hitam', styles: ['natural', 'klasik'], featured: 18,
  },
  {
    id: 'plakat-tangan-artistik', name: 'Plakat Tangan Artistik', category: 'plakat',
    subtitle: 'Bentuk tangan · Custom tinggi & lebar', badge: 'Bisa custom',
    price: null, image: 'assets/products/plakat-tangan-artistik.webp',
    thumbnail: 'assets/products/plakat-tangan-artistik.webp',
    alt: 'Plakat artistik berbentuk dua tangan bernuansa perunggu di atas alas',
    description: 'Komposisi dua tangan dengan tampilan bernuansa perunggu dan detail floral pada bagian dasar. Cocok sebagai referensi plakat penghargaan, dekorasi, atau karya custom.',
    note: 'Tinggi dan lebar bisa custom melalui chat WhatsApp. Harga, bahan, finishing, tulisan atau personalisasi, dan waktu pengerjaan dikonfirmasi sebelum produksi.',
    color: 'Perunggu', styles: ['klasik'], featured: 19,
  },
  {
    id: 'plakat-figur-penghargaan', name: 'Plakat Figur Penghargaan', category: 'plakat',
    subtitle: 'Figur emas · Custom tinggi & lebar', badge: 'Bisa custom',
    price: null, image: 'assets/products/plakat-figur-penghargaan.webp',
    thumbnail: 'assets/products/plakat-figur-penghargaan.webp',
    alt: 'Kumpulan plakat figur penghargaan berwarna emas dengan alas hitam',
    description: 'Figur penghargaan bernuansa emas dengan alas hitam. Foto menjadi referensi tampilan untuk plakat event, penghargaan, suvenir, atau pesanan custom.',
    note: 'Tinggi dan lebar bisa custom melalui chat WhatsApp. Desain, tulisan, harga, bahan, finishing, dan waktu pengerjaan dikonfirmasi sebelum produksi.',
    color: 'Emas & hitam', styles: ['klasik'], featured: 20,
  },
];
